### ISSUE TITLE
Enumerate a candidate list of APIs for Phase 1

### ISSUE THREAD

**Issue by debiandebiandebian** [MIC-TEAM/miccha-design#2]
## Motivation

`WATCHA` 의 모든 기능을 한 번에 구현하는 것은 힘들다.
흥미를 잃지 않기 위해, 여러 단계로 나누어 구현하는 것이 중요하다.
각 단계를 `Phase` 라고 하고, 여기서는 `Phase 1` 에 대해 다룬다.

`Phase 1` 에서는 `WATCHA` 의 기본 기능을 빠르게 구현하고자 한다.
실제 구현에 들어가기에 앞서, 구현할 기능과 `API` 를 정해야 한다.
위 내용이 확정된 후에나, 프론트 엔드 <> 백 엔드 분업이 가능할 것 같다.

## To do
- [x] `Phase 1` 에서 구현할 기능 나열하기
- [x] `Phase 1` 에서 구현할 `API` 나열하기

## Deadline
- 2021년 5월 11일 19:30

**Comment by debiandebiandebian** [comment]
## 구현할 만한 기능

1. 컨텐츠 목록을 여러 줄로 표시하는 기능
    - 기준이 있는 경우, 컨텐츠를 `묶어서` 표시한다.
        - 기준은 항상 서버가 제공한다.
        - 클라이언트는 기준에 대한 구현체가 있을 뿐이다.
    - `묶는다` 는 다음 의미를 가진다.
        - 각 줄에 표시되는 컨텐츠는 같은 기준에 속한다.
        - 각 줄은 기준을 잘 나타내는 제목을 갖는다.
    - 기준은 `중간에` 변경할 수 없다.

2. 첫 페이지에 컨텐츠 목록을 표시하는 기능
    - 서버에 첫 페이지에 표시할 컨텐츠 목록을 요청한다.
    - 1 을 사용해 컨텐츠 목록을 표시한다.

3. 특정 카테고리의 컨텐츠 목록을 표시하는 기능
    - 서버에 카테고리를 기준으로 한 컨텐츠 목록을 요청한다.
    - 1 을 사용해 컨텐츠 목록을 표시한다.

4. 검색 결과로 내려온 컨텐츠 목록을 표시하는 기능
    - 서버에 키워드에 맞는 컨텐츠 목록을 요청한다.
        - 서버는 기준 없이 컨텐츠 목록을 내려준다.
    - 1 을 사용해 컨텐츠 목록을 표시한다.

## 필요한 `API`

**Comment by devho813** [comment]
## 구현할 만한 기능

1. 컨텐츠 목록을 여러 줄로 표시하는 기능
    - 각 줄은 제목을 가질수도 있다.

2. ㅇ

2. 첫 페이지에 컨텐츠 목록을 표시하는 기능
    - 서버에 첫 페이지에 표시할 컨텐츠 목록을 요청한다.
    - 1 을 사용해 컨텐츠 목록을 표시한다.

3. 특정 카테고리의 컨텐츠 목록을 표시하는 기능
    - 서버에 특정 카테고리에 속하는 컨텐츠 목록을 요청한다.
        - 서버는 카테고리를 제목으로 달아 컨텐츠 목록을 내려준다.
    - 1 을 사용해 컨텐츠 목록을 표시한다.

4. 검색 결과로 내려온 컨텐츠 목록을 표시하는 기능
    - 서버에 키워드에 맞는 컨텐츠 목록을 요청한다.
        - 서버는 제목 없이 컨텐츠 목록을 내려준다.
    - 1 을 사용해 컨텐츠 목록을 표시한다.

## 필요한 `API`

## 참고
- https://medium.com/hashmapinc/rest-good-practices-for-api-design-881439796dc9
- https://www.ibm.com/docs/en/zosconnect/beta?topic=apis-designing-restful

**Comment by leemember** [comment]
영화 리뷰 (별점)
찜하기 기능 (보고싶어요)

**Comment by debiandebiandebian** [comment]
## `API`

| 기능  | `Method` | 경로 |
| ------------- | ------------- | ------------- |
| 컨텐츠 목록 가져오기  | `GET` | `/v1/movies` |
| 컨텐츠 세부 정보 가져오기 | `GET` | `/v1/movies/{movieId}` |
|로그인| ||
|회원가입 |`POST`| `/v1/users`|
|아이디 중복확인 | `GET` | `/v1/ids/{id}`|
|이메일 중복확인 | `GET` | `/v1/emails/{email}`|
|비밀번호 찾기|  |  |
